name: Sync README Line

on:
  schedule:
    - cron: "*/5 * * * *" # 每天凌晨 0 点自动运行（UTC 时间）
  workflow_dispatch: # 允许手动触发

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予写入权限

    steps:
      # 步骤 1：克隆当前仓库和目标仓库
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          #系统的权限 Token名称:secrets.ACTION_TOKEN 
          token: ${{ secrets.ACTION_TOKEN }} # 需配置权限 Token

      - name: Clone target repo
        run: |
          #引用的库 git clone https://github.com/xxx.git temp-repo
          git clone https://github.com/toshare5/toshare5.github.io.git temp-repo

      # 步骤 2：提取目标 README 的指定行
      - name: Extract line from target README
        id: extract-line
        run: |
          # 示例：提取第 29 行（注意，sed 行号从 1 开始计数）
          TARGET_LINE=$(sed -n '29p' temp-repo/README.md)
          # 将行内容（假设为 URL）设置为输出变量
          echo "::set-output name=url::$TARGET_LINE"

      # 步骤 3：使用提取的 URL 抓取网页内容并更新 README.md
      - name: Fetch web content and update README
        run: |
          # 使用 curl 获取网页内容（从上一个步骤的输出中获取URL）
          curl -sL "${{ steps.extract-line.outputs.url }}" > new_content.txt
          # 清空并覆写 README.md
          echo "" > README.md
          cat new_content.txt >> README.md

      # 步骤 4：提交更改
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update README from web content"
          git push
